package com.example.pirmaslab.mybatis.model;

import lombok.Getter;
import lombok.Setter;

public class Subject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.ID
     *
     * @mbg.generated Sun Apr 16 14:15:27 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.CREDITS
     *
     * @mbg.generated Sun Apr 16 14:15:27 EEST 2023
     */
    private Integer credits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SUBJECT.TITLE
     *
     * @mbg.generated Sun Apr 16 14:15:27 EEST 2023
     */
    private String title;

    @Getter
    @Setter
    private Long universityId;

    // Added manually
    @Getter
    @Setter
    private University university;

    @Getter
    @Setter
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.ID
     *
     * @return the value of PUBLIC.SUBJECT.ID
     *
     * @mbg.generated Sun Apr 16 14:15:27 EEST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.ID
     *
     * @param id the value for PUBLIC.SUBJECT.ID
     *
     * @mbg.generated Sun Apr 16 14:15:27 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.CREDITS
     *
     * @return the value of PUBLIC.SUBJECT.CREDITS
     *
     * @mbg.generated Sun Apr 16 14:15:27 EEST 2023
     */
    public Integer getCredits() {
        return credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.CREDITS
     *
     * @param credits the value for PUBLIC.SUBJECT.CREDITS
     *
     * @mbg.generated Sun Apr 16 14:15:27 EEST 2023
     */
    public void setCredits(Integer credits) {
        this.credits = credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SUBJECT.TITLE
     *
     * @return the value of PUBLIC.SUBJECT.TITLE
     *
     * @mbg.generated Sun Apr 16 14:15:27 EEST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SUBJECT.TITLE
     *
     * @param title the value for PUBLIC.SUBJECT.TITLE
     *
     * @mbg.generated Sun Apr 16 14:15:27 EEST 2023
     */
    public void setTitle(String title) {
        this.title = title;
    }
}