package com.example.pirmaslab.mybatis.model;

import com.example.pirmaslab.entities.Student;
import lombok.Getter;
import lombok.Setter;

import java.util.List;

public class University {

    //added manually
    @Getter @Setter
    private List<Student> students;

    @Getter @Setter
    private List<Student> subjects;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.UNIVERSITY.ID
     *
     * @mbg.generated Sun Apr 16 14:15:27 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.UNIVERSITY.TITLE
     *
     * @mbg.generated Sun Apr 16 14:15:27 EEST 2023
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.UNIVERSITY.ID
     *
     * @return the value of PUBLIC.UNIVERSITY.ID
     *
     * @mbg.generated Sun Apr 16 14:15:27 EEST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.UNIVERSITY.ID
     *
     * @param id the value for PUBLIC.UNIVERSITY.ID
     *
     * @mbg.generated Sun Apr 16 14:15:27 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.UNIVERSITY.TITLE
     *
     * @return the value of PUBLIC.UNIVERSITY.TITLE
     *
     * @mbg.generated Sun Apr 16 14:15:27 EEST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.UNIVERSITY.TITLE
     *
     * @param title the value for PUBLIC.UNIVERSITY.TITLE
     *
     * @mbg.generated Sun Apr 16 14:15:27 EEST 2023
     */
    public void setTitle(String title) {
        this.title = title;
    }
}