package com.example.pirmaslab.mybatis.dao;

import com.example.pirmaslab.mybatis.model.Subject;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface SubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECT
     *
     * @mbg.generated Sun Apr 16 14:15:27 EEST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECT
     *
     * @mbg.generated Sun Apr 16 14:15:27 EEST 2023
     */
    int insert(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECT
     *
     * @mbg.generated Sun Apr 16 14:15:27 EEST 2023
     */
    Subject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECT
     *
     * @mbg.generated Sun Apr 16 14:15:27 EEST 2023
     */
    List<Subject> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SUBJECT
     *
     * @mbg.generated Sun Apr 16 14:15:27 EEST 2023
     */
    int updateByPrimaryKey(Subject record);
}